# This file holds shared constants, like AgentRoles and AgentCapabilities,
# to avoid circular imports and keep definitions centralized.

class AgentCapabilities:
    """Defines the various capabilities or skills an AI agent can possess."""
    PLANNING = "planning"
    DESIGN = "design"
    VISUALIZATION = "visualization"
    ANALYSIS = "analysis"
    EXECUTION_MANAGEMENT = "execution_management"
    INTEGRATION = "integration"
    LEARNING = "learning"
    HUMAN_INTERACTION = "human_interaction"
    FINANCE = "finance"
    LEGAL = "legal"
    HR = "human_resources"
    SUSTAINABILITY = "sustainability"
    POST_CONSTRUCTION = "post_construction"
    PUBLIC_RELATIONS = "public_relations"
    REQUIREMENT_GATHERING = "requirement_gathering"
    NATURAL_LANGUAGE_PROCESSING = "natural_language_processing"
    GEOSPATIAL_ANALYSIS = "geospatial_analysis"
    REGULATORY_COMPLIANCE = "regulatory_compliance"

class AgentRoles:
    """Defines unique string identifiers (roles) for each agent in the system."""
    CLIENT_ENGAGEMENT = "strategic_client_engagement_agent"
    SITE_INTELLIGENCE = "site_intelligence_regulatory_compliance_agent"
    ARCHITECTURAL_DESIGN = "generative_architectural_design_agent"
    SYSTEMS_ENGINEERING = "integrated_systems_engineering_agent"
    EXPERIENTIAL_DESIGN = "interior_experiential_design_agent"
    DIGITAL_TWIN = "hyper_realistic_3d_digital_twin_agent"
    COST_SUPPLY_CHAIN = "predictive_cost_supply_chain_agent"
    PROJECT_MANAGEMENT = "adaptive_project_management_robotics_orchestration_agent"
    RISK_SAFETY = "proactive_risk_safety_management_agent"
    QUALITY_ASSURANCE = "ai_driven_quality_assurance_control_agent"
    DATA_INTEGRATION = "semantic_data_integration_ontology_agent"
    LEARNING_ADAPTATION = "learning_adaptation_agent"
    HUMAN_COLLABORATION = "human_ai_collaboration_explainability_agent"
    SUSTAINABILITY_GREEN = "sustainability_green_building_agent"
    FINANCIAL_INVESTMENT = "financial_investment_analysis_agent"
    LEGAL_CONTRACT = "legal_contract_management_agent"
    WORKFORCE_HR = "workforce_management_hr_agent"
    POST_CONSTRUCTION_FM = "post_construction_facility_management_agent"
    PUBLIC_RELATIONS_COMM = "public_relations_stakeholder_communication_agent"